config/routes.rb
Rails.application.routes.draw do
  resources :listings
  resources :agents
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/agent.rb
class Agent < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: %i[ show edit update destroy ]

  # GET /agents or /agents.json
  def index
    @agents = Agent.all
  end

  # GET /agents/1 or /agents/1.json
  def show
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents or /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to agent_url(@agent), notice: "Agent was successfully created." }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1 or /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to agent_url(@agent), notice: "Agent was successfully updated." }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1 or /agents/1.json
  def destroy
    @agent.destroy

    respond_to do |format|
      format.html { redirect_to agents_url, notice: "Agent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agent_params
      params.require(:agent).permit(:full_name, :email, :image, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :location, :address, :home_description, :home_type, :bed, :bath, :price, :sq_feet, :images)
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/agents/_agent.html.erb
<div id="<%= dom_id agent %>">
  <p>
    <strong>Full name:</strong>
    <%= agent.full_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= agent.email %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= agent.image %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= agent.description %>
  </p>

</div>

app/views/agents/_form.html.erb
<%= form_with(model: agent) do |form| %>
  <% if agent.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
        <% agent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Editing agent</h1>

<%= render "form", agent: @agent %>

<br>

<div>
  <%= link_to "Show this agent", @agent %> |
  <%= link_to "Back to agents", agents_path %>
</div>

app/views/agents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Agents</h1>

<div id="agents">
  <% @agents.each do |agent| %>
    <%= render agent %>
    <p>
      <%= link_to "Show this agent", agent %>
    </p>
  <% end %>
</div>

<%= link_to "New agent", new_agent_path %>

app/views/agents/new.html.erb
<h1>New agent</h1>

<%= render "form", agent: @agent %>

<br>

<div>
  <%= link_to "Back to agents", agents_path %>
</div>

app/views/agents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @agent %>

<div>
  <%= link_to "Edit this agent", edit_agent_path(@agent) %> |
  <%= link_to "Back to agents", agents_path %>

  <%= button_to "Destroy this agent", @agent, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealEstateApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :home_description, style: "display: block" %>
    <%= form.text_field :home_description %>
  </div>

  <div>
    <%= form.label :home_type, style: "display: block" %>
    <%= form.text_field :home_type %>
  </div>

  <div>
    <%= form.label :bed, style: "display: block" %>
    <%= form.text_field :bed %>
  </div>

  <div>
    <%= form.label :bath, style: "display: block" %>
    <%= form.text_field :bath %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :sq_feet, style: "display: block" %>
    <%= form.number_field :sq_feet %>
  </div>

  <div>
    <%= form.label :images, style: "display: block" %>
    <%= form.text_field :images %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/_listing.html.erb
<div id="<%= dom_id listing %>">
  <p>
    <strong>Title:</strong>
    <%= listing.title %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= listing.location %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= listing.address %>
  </p>

  <p>
    <strong>Home description:</strong>
    <%= listing.home_description %>
  </p>

  <p>
    <strong>Home type:</strong>
    <%= listing.home_type %>
  </p>

  <p>
    <strong>Bed:</strong>
    <%= listing.bed %>
  </p>

  <p>
    <strong>Bath:</strong>
    <%= listing.bath %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= listing.price %>
  </p>

  <p>
    <strong>Sq feet:</strong>
    <%= listing.sq_feet %>
  </p>

  <p>
    <strong>Images:</strong>
    <%= listing.images %>
  </p>

</div>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Show this listing", @listing %> |
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Listings</h1>

<div id="listings">
  <% @listings.each do |listing| %>
    <%= render listing %>
    <p>
      <%= link_to "Show this listing", listing %>
    </p>
  <% end %>
</div>

<%= link_to "New listing", new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @listing %>

<div>
  <%= link_to "Edit this listing", edit_listing_path(@listing) %> |
  <%= link_to "Back to listings", listings_path %>

  <%= button_to "Destroy this listing", @listing, method: :delete %>
</div>